server:
  port: 8090

chatbot-api:
  launchList: group01,group02 # 启动几组，就配置几组
  group01:
    groupName: ChatGLM AI 问答助手
    groupId: # 知识星球个人信息
    cookie:  # 知识星球个人cookie信息
  group02:
    groupName: ChatGLM AI 问答助手
    groupId: # 知识星球个人信息
    cookie:  # 知识星球个人cookie信息

chatGLM-api:
  launchList: group01,group02 # 启动几组，就配置几组
  group01:
    groupName: ChatGLM AI 问答助手
    api_key: # 自行申请ChatGLM https://open.bigmodel.cn/dev/api#http这是文档
    secret: # 去https://open.bigmodel.cn/usercenter/apikeys添加一个apikey
    cron: 0 0/1 * * * * ?
  group02:
    groupName: ChatGLM AI 问答助手
    api_key: # 自行申请ChatGLM https://open.bigmodel.cn/dev/api#http这是文档
    secret: # 去https://open.bigmodel.cn/usercenter/apikeys添加一个apikey
    cron: 0 0/1 * * * * ?


